In [16]:
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier as knc
import numpy as np
import matplotlib.pyplot as plt

In [17]:
# load dataset
iris = datasets.load_iris()

In [18]:
# use K nearest neighbour and set it to examine 7 closest neighbours
knn = knc(n_neighbors=7)

In [19]:
# Data in x and y below represented as np arrays
x = iris.data
y = iris.target

In [20]:
# x is the data/features - all measurements in cm
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
# y is the labels - iris species
# in the array representation 0 = setosa, 1 = versicolor, 2 = virginica
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
# pass the x and y values through the fit function to train the model
# this can be used to evaluate untrained data
knn.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=7, p=2,
           weights='uniform')

In [23]:
# test model with new data
# numpy array of 4 measurements for hypothetical iris plant
new_data1 = np.array([[4, 3, 2, 1]])

In [24]:
# apply the new data to the prediction function
# returns array representation 0 (setosa)
prediction1 = knn.predict(new_data1)
prediction1

array([0])

In [25]:
# to see iris species name
prediction1 = iris.target_names[knn.predict(new_data1)]
prediction1

array(['setosa'], dtype='<U10')

In [26]:
# further testing
new_data2 = np.array([[6, 3, 4, 1]])
prediction2 = iris.target_names[knn.predict(new_data2)]
prediction2

array(['versicolor'], dtype='<U10')

In [27]:
# further testing
new_data3 = np.array([[7, 4, 6, 2]])
prediction3 = iris.target_names[knn.predict(new_data3)]
prediction3 

array(['virginica'], dtype='<U10')